version: "3"

services:
  postgres:
    image: postgres:10.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=restfulnodejsapi
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/restfulnodejsapi
